title: Damien.LIVE
email: damien@redhat.com
description: >-
  DamienLIVE is a place where you can find blog posts, videos, photos and more from the mind and heart of Damien Eversmann.
baseurl: "/"
url: "https://www.damien.live"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: /blog/:year/:title:output_ext

collections:
  authors:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "category"
    values:
      layout: "category"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "damien"
