
permalink: /blog/:year/:title:output_ext

collections:
  authors:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "category"
    values:
      layout: "category"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "damien"
